Item.create!(
  [
    {
      name: 'パーカー',
      description: 'パーカーです',
      price: 1000,
      condition: 1,
      fee: 1,
      area: "北海道",
      shipping_days: 1,
      purchase_id: 2,
      brand_id: 1,
      user_id: 1,
      category_id: 33,
    },
    {
      name: 'ワンピース',
      description: 'ワンピースです',
      price: 3000,
      condition: 3,
      fee: 2,
      area: "東京都",
      shipping_days: 3,
      purchase_id: '',
      brand_id: 2,
      user_id: 1,
      category_id: 78,
    },
    {
      name: '靴',
      description: '靴です',
      price: 4000,
      condition: 2,
      fee: 2,
      area: "大阪府",
      shipping_days: 2,
      purchase_id: 2,
      brand_id: 3,
      user_id: 1,
      category_id: 84,
    },
    {
      name: '子供服',
      description: '子供服です',
      price: 5000,
      condition: 6,
      fee: 1,
      area: "愛知県",
      shipping_days: 1,
      purchase_id: '',
      brand_id: 4,
      user_id: 2,
      category_id: 153,
    },
    {
      name: 'スカート',
      description: 'スカートです',
      price: 6000,
      condition: 4,
      fee: 1,
      area: "沖縄県",
      shipping_days: 3,
      purchase_id: 1,
      brand_id: 5,
      user_id: 3,
      category_id: 73,
    },
    {
      name: 'バッグ',
      description: 'バッグです',
      price: 2000,
      condition: 5,
      fee: 2,
      area:  "福岡県",
      shipping_days: 3,
      purchase_id: '',
      brand_id: 6,
      user_id: 4,
      category_id: 83,
    },
  ]
)